services:
  ####################
  # Database + Cache #
  ####################
  db: # Core database of our app
    image: postgres:17.6-alpine3.22 # Always use fixed version
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_USER: ${DB_USER} # Login to connect to the database
      POSTGRES_PASSWORD: ${DB_PASSWORD} # User password
      POSTGRES_DB: ${DB_NAME} # Name of a database
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d # Add initial scripts
      - ./db/config:/etc/postgresql # Add config files
      # Note: Starting from the next version
      # 'data/' at the end should be omitted.
      # https://github.com/docker-library/postgres/pull/1259
      - ./db/data:/var/lib/postgresql/data # Add database files
    networks:
      # TODO: Use aliases
      - db
    shm_size: 128mb # Set shared memory limit when using docker compose
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432 # Port forwarding
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
      placement:
        constraints:
          - node.role == manager

  adminer: # Simple db web-manager
    image: adminer:5.4.1-standalone
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - db
    ports:
      - 8080:8080

networks:
  db:
    driver: bridge
